### ISSUE TITLE
Memory issue while xrd pattern 

### ISSUE THREAD

**Issue by asagotra** [dkriegner/xrayutilities#77]
I am trying to simulate xrd from set of cif  files. But I am not able to calculate xrd pattern in loop because memory getting full after 35 steps. MY computer configuration is I7, 32 gb Ram.
simpack.PowderModel()
intensities = pm.simulate()

**Comment by dkriegner** [comment]
which version of python/xrayutilities are you using? what is your operating system?

In the loop you use do you need all `PowderModel` instances after the loop is finished? Or can you delete them after use?

**Comment by asagotra** [comment]
I am using the latest version. My operating system is window.
Here, is my code:
for x  in range(0, 112056):
    print(x)
    try:
         xu_cif = CIFFile("cif/"+task_id[x])
         xu_crystal = Crystal(name="XRD" ,lat=xu_cif.SGLattice())
         powder = xru.simpack.smaterials.Powder(xu_crystal, 1)
         pm = xru.simpack.PowderModel(powder,I0=100)
         intensities = pm.simulate(two_theta)
         M.append(intensities)
         pm.close()
    except ValueError:
     print("some_error")

**Comment by dkriegner** [comment]
ok, i need to look into this in more detail.
The problem is related to issue #61 where only a workaround but no real fix was implemented.

**Comment by dkriegner** [comment]
The issue should be fixed. 
@asagotra: If you use GIT master (which you hopefully mean by latest?) you can test if the fix works also on windows. For installation of GIT master see https://sourceforge.net/p/xrayutilities/mailman/message/36512225/

I would be glad if you could report back in any case to let me know if it works or if you still get an error.

**Comment by asagotra** [comment]
Problem is still retain. The error I'm getting is "Cannot allocate memory".

**Comment by dkriegner** [comment]
thanks for the feedback. 
The `close()` is the important part for your kind of application. all changes I have done are in the close statement.
